/* AI Honeycomb Inspector v5 Professional — Report Builder + Exporter */
const Exporter = (() => {
  const METHOD = ["Inspect and mark all honeycomb locations.","Remove weak, loose and unsound concrete until sound concrete is reached.","Clean the repair area using brush, compressed air or water jet.","Pre-wet the surface to SSD condition where required by the repair product.","Apply bonding agent or cement slurry according to manufacturer specification.","Place non-shrink or polymer-modified repair mortar in compacted layers.","Finish the surface to match adjacent concrete.","Cure the repaired area properly and inspect after curing."];
  const MATERIALS=["Non-shrink repair mortar","Polymer-modified repair mortar","Bonding agent / cement slurry","Clean water","Curing compound","Hand tools and wire brush"];
  function val(id){const el=document.getElementById(id);return el?el.value.trim():""}
  function getFormData(){return{project:val("f_project")||"—",subject:val("f_subject")||"Honeycomb Defect Assessment",location:val("f_location")||"—",structType:val("f_structural_type")||"—",structName:val("f_structural_name")||"—",date:val("f_date")||new Date().toISOString().slice(0,10),inspector:val("f_inspector")||"—",company:val("f_company")||"Construction Intelligence Laboratory",weather:val("f_weather")||"—",remark:val("f_remark")||"—"}}
  function getSeverity(count,totalArea=0){ if(count<=0)return{name:"No Defect Detected",level:"Low",color:"#34c759",rgb:[52,199,89]}; if(count<=2&&totalArea<30)return{name:"Minor",level:"Low",color:"#34c759",rgb:[52,199,89]}; if(count<=5&&totalArea<120)return{name:"Moderate",level:"Medium",color:"#ff9500",rgb:[255,149,0]}; return{name:"Severe",level:"High",color:"#ff3b30",rgb:[255,59,48]};}
  function fmt(n,d=2){return Number(n||0).toFixed(d)} function fmtDate(iso){if(!iso)return"—";const a=iso.split("-");return a.length===3?`${a[2]}/${a[1]}/${a[0]}`:iso} function esc(s){return String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[m]))}
  function buildReportData(state){
    const form=getFormData(), captures=state.captures||[]; const all=captures.flatMap(c=>c.detections||[]); const count=captures.reduce((s,c)=>s+(c.voids||0),0); const total=captures.reduce((s,c)=>s+(c.totalAreaCm2||0),0); const largest=captures.reduce((m,c)=>Math.max(m,c.largestAreaCm2||0),0); const confs=all.map(d=>d.confidence||d.score||0).filter(n=>n>0); const avgConf=confs.length?confs.reduce((a,b)=>a+b,0)/confs.length:0; const sev=getSeverity(count,total);
    return{form,captures,allDetections:all,count,totalAreaCm2:total,largestAreaCm2:largest,avgConfidence:avgConf,severity:sev,reportNo:`HI-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`,generated:new Date().toLocaleString(),method:METHOD,materials:MATERIALS};
  }
  function renderReportHTML(r){
    const detRows=(r.allDetections.length?r.allDetections:[{id:"—",areaCm2:0,confidence:0}]).map((d,i)=>`<tr><td>Honeycomb #${i+1}</td><td>${fmt(d.areaCm2)} cm²</td><td>${fmt((d.confidence||d.score||0)*100,0)}%</td><td>${getSeverity(1,d.areaCm2||0).name}</td><td>${suggestRepair(d.areaCm2||0)}</td></tr>`).join("");
    const photoCards=r.captures.length?r.captures.map((c,i)=>`<div class="photo-card"><img src="${c.dataUrl}"/><div class="photo-meta"><div><span>Photo</span><strong>#${i+1}</strong></div><div><span>Voids</span><strong>${c.voids}</strong></div><div><span>Largest Area</span><strong>${fmt(c.largestAreaCm2)} cm²</strong></div><div><span>Time</span><strong>${esc(c.ts)}</strong></div></div></div>`).join(""):`<div class="assessment">No captured photos were attached to this report.</div>`;
    return `<div class="r-cover"><div class="r-top"><div style="display:flex;gap:16px"><div class="r-logo">AI</div><div class="r-title"><h2>AI Concrete Condition Assessment Report</h2><p>Professional Honeycomb Inspection · ${esc(r.form.company)}</p><p><b>Report No:</b> ${r.reportNo} · <b>Generated:</b> ${esc(r.generated)}</p></div></div><div class="r-badge" style="background:${r.severity.color}">${r.severity.name}</div></div></div>
    <section class="r-section"><h3>1. Executive Summary</h3><div class="r-cards"><div class="r-card"><span>Project</span><strong>${esc(r.form.project)}</strong></div><div class="r-card"><span>Structural Element</span><strong>${esc(r.form.structType)} ${esc(r.form.structName)}</strong></div><div class="r-card"><span>Inspection Status</span><strong>Completed</strong></div><div class="r-card"><span>Inspector</span><strong>${esc(r.form.inspector)}</strong></div><div class="r-card"><span>Location</span><strong>${esc(r.form.location)}</strong></div><div class="r-card"><span>Inspection Date</span><strong>${fmtDate(r.form.date)}</strong></div></div></section>
    <section class="r-section"><h3>2. Inspection Statistics</h3><div class="r-cards"><div class="r-card"><span>Total Honeycombs</span><strong>${r.count}</strong></div><div class="r-card"><span>Largest Area</span><strong>${fmt(r.largestAreaCm2)} cm²</strong></div><div class="r-card"><span>Total Area</span><strong>${fmt(r.totalAreaCm2)} cm²</strong></div><div class="r-card"><span>Average Confidence</span><strong>${fmt(r.avgConfidence*100,0)}%</strong></div><div class="r-card"><span>Captured Photos</span><strong>${r.captures.length}</strong></div><div class="r-card"><span>Risk Level</span><strong style="color:${r.severity.color}">${r.severity.level}</strong></div></div></section>
    <section class="r-section"><h3>3. Detection Overview</h3><table class="r-table"><thead><tr><th>Photo</th><th>Honeycombs</th><th>Largest Area</th><th>Severity</th><th>Time</th></tr></thead><tbody>${r.captures.map((c,i)=>`<tr><td>Photo ${i+1}</td><td>${c.voids}</td><td>${fmt(c.largestAreaCm2)} cm²</td><td>${esc(c.severity)}</td><td>${esc(c.ts)}</td></tr>`).join("")||`<tr><td colspan="5">No captures</td></tr>`}</tbody></table></section>
    <section class="r-section"><h3>4. Captured Images</h3>${photoCards}</section>
    <section class="r-section"><h3>5. Individual Defect Analysis</h3><table class="r-table"><thead><tr><th>Defect</th><th>Area</th><th>Confidence</th><th>Severity</th><th>Suggested Repair</th></tr></thead><tbody>${detRows}</tbody></table></section>
    <section class="r-section"><h3>6. AI Engineering Assessment</h3><div class="assessment">${assessmentText(r)}</div></section>
    <section class="r-section"><h3>7. Risk Assessment</h3><div class="assessment"><b style="color:${r.severity.color}">Current Risk: ${r.severity.level}</b><br>${riskText(r)}</div></section>
    <section class="r-section"><h3>8. Repair Recommendation</h3><div class="r-cards"><div class="r-card"><span>Recommended Method</span><strong>${recommendedMethod(r)}</strong></div><div class="r-card"><span>Further Action</span><strong>${r.severity.level==="High"?"Engineer Review":"Repair + Reinspect"}</strong></div><div class="r-card"><span>Materials</span><strong>${MATERIALS.slice(0,3).join(", ")}</strong></div></div></section>
    <section class="r-section"><h3>9. General Method Statement</h3><div class="method-flow">${METHOD.map((m,i)=>`<div>${i+1}. ${esc(m)}</div>`).join("")}</div></section>
    <section class="r-section"><h3>10. Inspector Verification</h3><div class="signature-row"><div><div class="sig-line"></div><p>Inspector Signature</p></div><div><div class="sig-line"></div><p>Engineer / Company Approval</p></div><div class="qr-box">QR CODE<br>Digital Report</div></div></section>
    <div class="report-footer"><span>Generated by AI Honeycomb Inspector Professional v5.0</span><span>Construction Intelligence Laboratory (CI-Lab)</span></div>`;
  }
  function assessmentText(r){ if(r.count===0)return"No visible honeycomb defects were detected in the captured inspection records. The inspected surface may be accepted visually, subject to final site engineer confirmation."; return`The inspection identified ${r.count} honeycomb defect(s) with an estimated total affected area of ${fmt(r.totalAreaCm2)} cm². The largest detected area is ${fmt(r.largestAreaCm2)} cm². Based on the captured images, the overall condition is classified as ${r.severity.name}. Surface repair is recommended, and if exposed reinforcement or deep cavities are confirmed on site, further structural assessment should be performed before repair.`}
  function riskText(r){ if(r.count===0)return"No visual defect risk was detected by the AI model in the captured photos."; if(r.severity.level==="Low")return"Detected defects appear limited and may be treated as localized surface honeycomb after engineer confirmation."; if(r.severity.level==="Medium")return"Moderate honeycomb was detected. Repair is recommended and the depth of defect should be checked before final acceptance."; return"High risk condition. Immediate engineer review is recommended, especially if the member is load-bearing or reinforcement is exposed."}
  function recommendedMethod(r){ if(r.count===0)return"No repair required"; if(r.severity.level==="High")return"Engineer review + repair method approval"; return"Surface patch repair"} function suggestRepair(area){return area>80?"Engineer review":"Patch repair"}

  async function exportPNG(report){ if(!report){alert("Generate report preview first.");return;} const c=await renderCanvas(report); const a=document.createElement("a"); a.download=`honeycomb_professional_report_${Date.now()}.png`; a.href=c.toDataURL("image/png"); document.body.appendChild(a); a.click(); a.remove(); }
  async function exportPDF(report){ if(!report){alert("Generate report preview first.");return;} if(typeof window.jspdf==="undefined"){alert("PDF library not loaded. Check internet connection.");return;} const {jsPDF}=window.jspdf; const c=await renderCanvas(report); const pdf=new jsPDF({orientation:"portrait",unit:"mm",format:"a4"}); const pageW=210,pageH=297; const imgW=pageW; const imgH=c.height*imgW/c.width; let y=0; pdf.addImage(c.toDataURL("image/jpeg",.92),"JPEG",0,y,imgW,imgH); let heightLeft=imgH-pageH; while(heightLeft>0){y-=pageH; pdf.addPage(); pdf.addImage(c.toDataURL("image/jpeg",.92),"JPEG",0,y,imgW,imgH); heightLeft-=pageH;} pdf.save(`honeycomb_professional_report_${Date.now()}.pdf`); }

  async function renderCanvas(r){
    const W=1200,P=54,photoH=520; const photoBlock=r.captures.length?r.captures.length*(photoH+108):120; const H=1600+photoBlock+Math.max(0,r.allDetections.length)*26; const c=document.createElement("canvas"); c.width=W;c.height=H; const x=c.getContext("2d"); x.fillStyle="#f6f8fc";x.fillRect(0,0,W,H); let y=42; card(x,P,y,W-P*2,190,28,"#fff"); x.fillStyle="#0f172a";x.font="bold 38px Arial";x.fillText("AI Concrete Condition Assessment Report",P+32,y+62); x.font="18px Arial";x.fillStyle="#64748b";x.fillText(`Professional Honeycomb Inspection · ${r.form.company}`,P+32,y+98); pill(x,W-P-230,y+38,190,46,r.severity.name,r.severity.color); x.font="15px Arial";x.fillText(`Report No: ${r.reportNo} · Generated: ${r.generated}`,P+32,y+140); y+=232;
    section(x,"1. EXECUTIVE SUMMARY",P,y); y+=34; const info=[["Project",r.form.project],["Subject",r.form.subject],["Location",r.form.location],["Element",`${r.form.structType} ${r.form.structName}`],["Inspector",r.form.inspector],["Date",fmtDate(r.form.date)]]; drawCards(x,info,P,y,W-P*2,3); y+=190;
    section(x,"2. INSPECTION STATISTICS",P,y); y+=34; drawCards(x,[["Total Honeycombs",r.count],["Largest Area",`${fmt(r.largestAreaCm2)} cm²`],["Total Area",`${fmt(r.totalAreaCm2)} cm²`],["Average Confidence",`${fmt(r.avgConfidence*100,0)}%`],["Captured Photos",r.captures.length],["Risk Level",r.severity.level]],P,y,W-P*2,3); y+=190;
    section(x,"3. CAPTURED IMAGES",P,y); y+=36; if(!r.captures.length){card(x,P,y,W-P*2,90,18,"#fff");x.fillStyle="#64748b";x.font="18px Arial";x.fillText("No captured photos were attached.",P+26,y+54);y+=118;} else {for(let i=0;i<r.captures.length;i++){await imageCard(x,r.captures[i],i,P,y,W-P*2,photoH);y+=photoH+108;}}
    section(x,"4. AI ENGINEERING ASSESSMENT",P,y); y+=34; y=textBox(x,assessmentText(r),P,y,W-P*2,120)+28;
    section(x,"5. RISK ASSESSMENT",P,y); y+=34; y=textBox(x,`Current Risk: ${r.severity.level}. ${riskText(r)}`,P,y,W-P*2,110)+28;
    section(x,"6. REPAIR RECOMMENDATION",P,y); y+=34; drawCards(x,[["Recommended Method",recommendedMethod(r)],["Further Action",r.severity.level==="High"?"Engineer Review":"Repair + Reinspect"],["Materials",MATERIALS.slice(0,3).join(", ")]],P,y,W-P*2,3); y+=112;
    section(x,"7. GENERAL METHOD STATEMENT",P,y); y+=34; card(x,P,y,W-P*2,270,18,"#fff"); x.fillStyle="#334155";x.font="17px Arial"; let my=y+34; METHOD.forEach((m,i)=>{wrap(x,`${i+1}. ${m}`,W-P*2-52).forEach(line=>{x.fillText(line,P+26,my);my+=24});my+=4}); y+=305;
    section(x,"8. INSPECTOR VERIFICATION",P,y); y+=34; card(x,P,y,W-P*2,130,18,"#fff"); x.strokeStyle="#94a3b8";x.lineWidth=2; x.beginPath();x.moveTo(P+30,y+86);x.lineTo(P+400,y+86);x.moveTo(P+470,y+86);x.lineTo(P+840,y+86);x.stroke(); x.fillStyle="#64748b";x.font="14px Arial";x.fillText("Inspector Signature",P+30,y+108);x.fillText("Engineer / Company Approval",P+470,y+108); x.strokeRect(W-P-145,y+25,96,80);x.fillText("QR CODE",W-P-128,y+68); y+=164; x.fillStyle="#64748b";x.font="15px Arial";x.fillText("Generated by AI Honeycomb Inspector Professional v5.0 · Construction Intelligence Laboratory (CI-Lab)",P,y); return c;
  }
  function card(ctx,x,y,w,h,r,bg){ctx.fillStyle=bg;round(ctx,x,y,w,h,r);ctx.fill();ctx.strokeStyle="#dbe3ef";ctx.stroke()} function round(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()} function pill(ctx,x,y,w,h,t,bg){ctx.fillStyle=bg;round(ctx,x,y,w,h,23);ctx.fill();ctx.fillStyle="#fff";ctx.font="bold 18px Arial";ctx.textAlign="center";ctx.fillText(t,x+w/2,y+30);ctx.textAlign="left"} function section(ctx,t,x,y){ctx.fillStyle="#0f172a";ctx.font="bold 18px Arial";ctx.fillText(t,x,y)} function drawCards(ctx,items,x,y,w,cols){const gap=14,cw=(w-gap*(cols-1))/cols;items.forEach((it,i)=>{const cx=x+(i%cols)*(cw+gap),cy=y+Math.floor(i/cols)*82;card(ctx,cx,cy,cw,66,16,"#fff");ctx.fillStyle="#64748b";ctx.font="12px Arial";ctx.fillText(String(it[0]).toUpperCase(),cx+16,cy+24);ctx.fillStyle="#0f172a";ctx.font="bold 20px Arial";fit(ctx,String(it[1]),cx+16,cy+50,cw-32)})} function fit(ctx,t,x,y,max){let s=t;while(ctx.measureText(s).width>max&&s.length>3)s=s.slice(0,-2);ctx.fillText(s.length<t.length?s+"…":s,x,y)} async function imageCard(ctx,cap,i,x,y,w,h){card(ctx,x,y,w,h+78,20,"#fff");await new Promise(res=>{const img=new Image();img.onload=()=>{ctx.save();round(ctx,x+16,y+16,w-32,h,14);ctx.clip();drawContain(ctx,img,x+16,y+16,w-32,h);ctx.restore();ctx.fillStyle="#0f172a";ctx.font="bold 18px Arial";ctx.fillText(`Photo ${i+1}`,x+20,y+h+48);ctx.fillStyle="#64748b";ctx.font="15px Arial";ctx.fillText(`${cap.ts} · ${cap.voids} voids · largest ${fmt(cap.largestAreaCm2)} cm²`,x+120,y+h+48);res()};img.onerror=res;img.src=cap.dataUrl})} function drawContain(ctx,img,x,y,w,h){const s=Math.min(w/img.width,h/img.height),nw=img.width*s,nh=img.height*s;ctx.fillStyle="#0f172a";ctx.fillRect(x,y,w,h);ctx.drawImage(img,x+(w-nw)/2,y+(h-nh)/2,nw,nh)} function textBox(ctx,t,x,y,w,minH){const lines=wrap(ctx,t,w-52);const h=Math.max(minH,lines.length*25+42);card(ctx,x,y,w,h,18,"#fff");ctx.fillStyle="#334155";ctx.font="17px Arial";let yy=y+34;lines.forEach(l=>{ctx.fillText(l,x+26,yy);yy+=25});return y+h} function wrap(ctx,t,max){const words=String(t).split(" "),lines=[];let line="";for(const w of words){const test=line?line+" "+w:w;if(ctx.measureText(test).width>max&&line){lines.push(line);line=w}else line=test}if(line)lines.push(line);return lines}
  return{buildReportData,renderReportHTML,exportPNG,exportPDF,getSeverity};
})();
